server:
  shutdown: GRACEFUL
  port: 9090
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: rule
  kafka:
    bootstrap-servers:
      - localhost:9092
  cloud:
    stream:
      function:
        definition: reset-withdraw
      bindings:
        reset-withdraw-int-0:
          destination: reset-withdraw
          group: ${spring.application.name}
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000
    url: jdbc:postgresql://localhost:5433/postgres
    password: root
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
  flyway:
    locations:
      - classpath:db/migration
